version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      "POSTGRES_USER": "postgres"
      "POSTGRES_PASSWORD": "0252"
      "POSTGRES_DB": "ppo"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - testnet

  app:

    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:0252@db:5432/ppo?sslmode=disable
    networks:
      - testnet
    command: ["go", "test", "./..."]

networks:
  testnet:

volumes:
  postgres_data:
